### ISSUE TITLE
"Arms" vs "tiles" rotation

### ISSUE THREAD

**Issue by gordonwoodhull** [gordonwoodhull/hexapipes#2]
This fork of hexapipes implements "arms" rotation, where the rotation is passed into `grid.getPipesPath()` and the grid is responsible for rotating the arms to match.

In base hexapipes, the entire tile is rotated and pipes don't need to be redrawn per tile.

Only `PenroseGrid` supports "arms" rotation, so other grids do not currently rotate their tiles when clicked.

"Arms" rotation should be refactored to be optional, and should only be applied to `PenroseGrid`. It could be useful for other grids where angles between arm positions are non-uniform.

**Comment by gereleth** [comment]
A related problem is that "click to orient" control mode doesn't work correctly on penrose grid.
