### ISSUE TITLE
Trihexagonal puzzle generation fails in this fork

### ISSUE THREAD

**Issue by gordonwoodhull** [gordonwoodhull/hexapipes#5]
Either I made a mistake when rebasing, or there are divergent assumptions in the code.

> 'Could not generate a puzzle with a unique solution. Maybe try again.'

This is the only grid that completely fails to appear... probably it is something stupid, and easy to fix once identified.

**Comment by gereleth** [comment]
This is probably due to opposite directions handling. Trihexagonal grid doesn't return opposite direction from find_neighbour.

**Comment by gordonwoodhull** [comment]
Aha, thanks for the hint! Makes sense.
