### ISSUE TITLE
"Click to orient" control mode doesn't work correctly on Penrose grid

### ISSUE THREAD

**Issue by gordonwoodhull** [gordonwoodhull/hexapipes#6]
A related problem is that "click to orient" control mode doesn't work correctly on penrose grid.

_Originally posted by @gereleth in https://github.com/gordonwoodhull/hexapipes/issues/2#issuecomment-1741701969_

**Comment by gordonwoodhull** [comment]
Should be the same root cause as #6 - looks like it is working correctly on its own, but not reflected in the display because the tile and dots are not rotated.

**Comment by gordonwoodhull** [comment]
It's related to #2 but a bit more complicated. The guide dot in other grids relies on the rotation transform, but the Penrose grid doesn't use a rotation transform.

An easy solution would be to apply the tile + rotation transforms only to the dot. However, I think this would look funny because the dot would be squished, especially on the skinny rhombs. So the right way to do this is passing the rotations into `getGuideDotPosition()` like we are doing for `getPipesPath()`, and apply the tile transform + rotation to the coordinate using the transformation-matrix object on the polygon.

**Comment by gordonwoodhull** [comment]
<strike>There is something else going on, because sometimes the tiles get colored as if rotation is working, but don't actually move.</strike>

![image](https://github.com/gordonwoodhull/hexapipes/assets/1366709/eb69aeb9-c1e5-48e5-a88b-6067321d4729)

Confusing!

**Comment by gordonwoodhull** [comment]
Not seeing the previous behavior, but keeping previous comment in case it returns.

I'm currently seeing:
1. dot is not necessarily drawn at correct place initially
2. after clicking on dot, tile will orient to a place where the dot sort of (5) makes sense. but the initial click may also put the tile into negative rotations (4).
3. after that, clicking clockwise will "wind up" the tile with positive rotations. when the tile has positive rotations, clicking will consistent with moving the dot to that position, although the dot doesn't move.
4. however, clicking counter-clockwise puts the tile into negative total rotations, and these only display correctly on the even negative numbers. on the odd negative numbers, they are displayed opposite
5. the dot only sort of makes sense - it's on the correct side, but often displayed toward corner when it should be center, or vice versa

**Comment by gereleth** [comment]
There's definitely something funky going on with directions because I see "connected" tiles having different colors like this: 
![image](https://github.com/gordonwoodhull/hexapipes/assets/6080076/826250f9-7bcf-4d14-8ac7-f1d646bd6d5c)

This must mean that the displayed rotation does not correspond to connections state. It's confusing...

I had a hunch that click to orient mode was not aware enough of `fix_rotation_offsets` but I haven't found anything concrete yet.

Maybe you can remove this mode for the release milestone and work on it at the merge upstream stage)).

**Comment by gordonwoodhull** [comment]
I think these are all caused by odd negative rotations being being drawn backward. If you spin it clockwise until `tileState.data.rotations` is positive, my hypothesis is that the colors will repair.

Yeah, I've considered disabling orient/lock for release. We'll see, I'm going to look a little more. This is the last remaining issue for release. 🥳

**Comment by gordonwoodhull** [comment]
Okay, I fixed an array rotation bug causing the above backward/reversed tiles, and implemented the tile transform for the dot.

I'll open follow-up issues to implement this correctly for upstream.

I get residual vertigo if I look at the perspective on the dots, but I don't think it's too dangerous to ship.
